pipeline {
    agent node3

    environment {
    WorkDir = "apis/user-java"
    ImgName = "arnoxuweichu/user-java"
    ImgTag = "${params.ImgTag}"
    Test = "ABC"
    }

    parameters {
    booleanParam defaultValue: true, description: '''True: upload image
    False: do not upload image''', name: 'upload image'
    string defaultValue: '1.0', description: 'Set default image tag to 1.0', name: 'ImgTag', trim: true
    }

    stages {
        stage('Testing Types of Ref'){
            echo 'Test'
            echo '$Test'
            echo '${Test}'
        }
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image $ImgName:$ImgTag ...'
                dir(WorkDir) {
                    sh 'pwd'
                    sh 'sudo docker build -t $ImgName:$ImgTag .'
                }
            }
        }


        stage('Upload Docker Image') {
            when {
  		        expression {return params.blUploadImg}
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'DockerHub', passwordVariable: 'DockerHubPwd', usernameVariable: 'DockerHubUsr')]) {
                    echo 'Dockerhub Login'
                    sh 'sudo docker login -u $dockerUsr -p $dockerPwd'
                    sh "sudo docker push ${ImgName}:${params.ImgTag}"
                }
            }
        }
    }
}