pipeline {
    agent any

    environment {
    WorkDir = "apis/user-java"
    ImgName = "arnoxuweichu/user-java"
    ImgTag = "${params.ImgTag}"
    }

    parameters {
    booleanParam defaultValue: true, description: '''True: upload image
    False: do not upload image''', name: 'upload image'
    string defaultValue: '1.0', description: 'Set default image tag to 1.0', name: 'ImgTag', trim: true
    }

    stages {
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image $ImgName:$ImgTag ...'
                dir(WorkDir) {
                    sh 'pwd'
                    sh 'sudo docker build -t $ImgName:$ImgTag .'
                    // One or more steps need to be included within the steps block.
                }
            }
        }


        stage('Upload Docker Image') {
            when {
                environment name: 'upload image', value: '1'
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'willido_dockerhub', passwordVariable: 'dockerPwd', usernameVariable: 'dockerUsr')]) {
                    echo 'Dockerhub Login'
                    sh 'sudo docker login -u $dockerUsr -p $dockerPwd'
                    sh "sudo docker push ${ImgName}:${params.ImgTag}"
                }
            }
        }
    }
}